#!/bin/bash

function run {
    killall vlc eog &> /dev/null
    python3 ./deploy/hephaestus/rose.py 
    latest_png=$(ls -t ./deploy/hephaestus/logs/*.png | head -n 1)
    latest_avi=$(ls -t ./deploy/hephaestus/logs/*.avi | head -n 1)
    if [ -n "$latest_png" ]; then
        eog "$latest_png" &> /dev/null &
    fi
    if [ -n "$latest_avi" ]; then
        vlc --no-qt-fs-controller "$latest_avi" &> /dev/null &
    fi
}

function edit {
    case $1 in
        gym_conf)
            gedit ./deploy/config/config_gym_InvertedPendulumFine-v4.yaml &> /dev/null &
            ;;
        sim_conf)
            gedit ./deploy/config/config_deploy_gym.yaml &> /dev/null &
            ;;
        firesim_conf)
            gedit ./soc/sim/config/config_runtime_local.yaml &> /dev/null &
            ;;
        pid_sw)
            gedit ./soc/sw/baremetal/inverted-pendulum-pid.c &> /dev/null &
            ;;
        *)
            echo "Unknown configuration. Please specify one of: gym_conf, sim_conf, firesim_conf, pid_sw"
            ;;
    esac
}

function view_logs {
    nautilus ./deploy/hephaestus/logs/ &> /dev/null &
}

function view_dnn {
    size=$1
    model_path="./soc/sw/rose-images/airsim-driver-fed/overlay/root/drone_offline_test -m ./soc/sw/rose-images/airsim-driver-fed/overlay/root/trail_resnet${size}_complex.onnx"

    killall netron &> /dev/null
    sleep 1
    
    if [ -f "$model_path" ]; then
        netron "$model_path" &> /dev/null &
    else
        echo "Model file not found: $model_path"
    fi
}


function vm_ros {
    marshal launch ./soc/sw/rose-images/ros-ubuntu.json
}

function infrasetup {
    firesim infrasetup
}

function dnn {
    platform=$1
    size=$2
    
    if [ "$platform" == "gemmini" ]; then
        mode=2
    elif [ "$platform" == "cpu" ]; then
        mode=0
    else
        echo "Invalid platform. Please specify 'cpu' or 'gemmini'."
        exit 1
    fi
    
    if ! [[ $size =~ ^(6|14|34)$ ]]; then
        echo "Invalid size. Please specify one of: 6, 14, 34."
        exit 1
    fi

    killall vlc eog &> /dev/null
    sleep 1
    eog "./soc/sw/rose-images/airsim-driver-fed/overlay/root/img/img_56.png" &> /dev/null &
    
    spike --extension=gemmini pk ./soc/sw/rose-images/airsim-driver-fed/overlay/root/drone_offline_test -m ./soc/sw/rose-images/airsim-driver-fed/overlay/root/trail_resnet${size}_complex.onnx -i ./soc/sw/rose-images/airsim-driver-fed/overlay/root/img/img_56.png -p unit -x ${mode} -O 99 -v 6.0
}

case $1 in
    run)
        run
        ;;
    edit)
        edit $2
        ;;
    view)
        if [ "$2" = "logs" ]; then
            view_logs
        elif [ "$2" = "dnn" ]; then
            view_dnn $3
        else
            echo "Unknown view command. Please specify one of: logs, dnn"
        fi
        ;;
    vm)
        if [ "$2" = "ros" ]; then
            vm_ros
        else
            echo "Unknown VM command. Please specify one of: ros"
        fi
        ;;
    build)
        infrasetup
        ;;
    dnn)
        dnn $2 $3
        ;;
    *)
        echo "Unknown command. Please specify one of: run, build, dnn, edit, view, vm"
        ;;
esac
