packets:
  - name: camera_stereo
    id: 0x10
    type: "reqrsp"
    latency: 0
    channel: 1
    indices:
      - "camera"

  - name: 'camera_loopback'
    id: 0x01
    type: "loopback"
    indices:
      - "camera"


channel_bandwidth: 
  - 0
  - 0
  - 0

gym_timestep: 0.001
  
gym_kwargs:
  init_x: 0
  init_y: 0

