packets:
  - name: camera_stereo
    id: 0x10
    type: "reqrsp"
    latency: 0
    channel: 1
    indices:
      - "camera"
  # actions
  - name: 'arm'
    id: 0x01
    type: "action_latch"
    indices:
      - "active"
  - name: 'disarm'
    id: 0x02
    type: "action_latch"
    indices:
      - "active"
  - name: 'takeoff'
    id: 0x04
    type: "action_latch"
    indices:
      - "active"

channel_bandwidth: 
  - 0
  - 0
  - 0

gym_timestep: 0.001
  
gym_kwargs:
  init_x: 0
  init_y: 0

