packets:
  - name: observation
    id: 0x16
    type: "reqrsp"
    latency: 0
    channel: 0
    indices:
  - name: action
    id: 0x20
    type: "action_latch"
    indices:
defaults:
  action: [0]
gym_timestep: 0.04
gym_kwargs:

