#!/usr/bin/env bash
# gen_firesim_run_config.sh — generate a FireSim manager run config (+ workload json) for a RoSE
# simulation, with all machine/user-specific paths derived from the environment instead of
# hardcoded. This exists because the live `config_runtime_*.yaml` files in the chipyard submodule
# bake in absolute paths (`/scratch/<user>/...`), an SSH run-farm host, and an fpga_db path — none
# of which are portable, so they are NOT committed. Regenerate yours with this script.
#
# Usage:
#   soc/scripts/gen_firesim_run_config.sh [options]
#
# Options (all optional; sensible defaults shown):
#   --hw-config KEY     hwdb/build-recipe key -> default_hw_config
#                       (default: alveo_u250_firesim-rocket-saturn-with-rose-fast-no-nic-l2-llc4mb-ddr3)
#   --workload NAME     workload name, with or without .json (default: rose-nav)
#   --bootbinary FILE   guest ELF the workload boots (default: zephyr.elf)
#   --outputs "a b"     space-separated common_simulation_outputs (default: "uartlog";
#                       the TACIT flow also needs "tacit0.out")
#   --run-host HOST     run-farm host. "localhost" (default) for the local U250, or
#                       "user@host.domain" to drive a remote FPGA over SSH.
#   --sim-dir DIR       default_simulation_dir (default: $ROSE_ROOT/soc/sim/firesim_run_temp)
#   --fpga-db FILE      default_fpga_db (only emitted for a remote --run-host; default: none)
#   --name NAME         basename for the generated config (default: derived from --run-host)
#   -h|--help           this help
#
# Examples:
#   # local U250, 3-gate nav flight:
#   soc/scripts/gen_firesim_run_config.sh --workload rose-nav \
#       --hw-config alveo_u250_firesim-rocket-saturn-with-rose-fast-no-nic-l2-llc4mb-ddr3
#
#   # remote firesim1 U250:
#   soc/scripts/gen_firesim_run_config.sh --workload rose-nav --name firesim1 \
#       --run-host "youruser@firesim1.millennium.berkeley.edu" \
#       --fpga-db /scratch/youruser/rose-fsim/fpga_target.json
#
#   # local TACIT instruction-trace capture:
#   soc/scripts/gen_firesim_run_config.sh --workload rose-tacit --name local_tacit \
#       --outputs "uartlog tacit0.out" \
#       --hw-config alveo_u250_firesim-rocket-saturn-tacit-with-rose-fast-no-nic-l2-llc4mb-ddr3
#
# The generated files land in  soc/sim/chipyard/sims/firesim/deploy/ :
#   config_runtime_<name>.yaml   and   workloads/<workload>.json
set -euo pipefail

ROSE_ROOT="$(git -C "$(dirname "${BASH_SOURCE[0]}")" rev-parse --show-toplevel)"
DEPLOY="$ROSE_ROOT/soc/sim/chipyard/sims/firesim/deploy"

HW_CONFIG="alveo_u250_firesim-rocket-saturn-with-rose-fast-no-nic-l2-llc4mb-ddr3"
WORKLOAD="rose-nav"
BOOTBINARY="zephyr.elf"
OUTPUTS="uartlog"
RUN_HOST="localhost"
SIM_DIR="$ROSE_ROOT/soc/sim/firesim_run_temp"
FPGA_DB=""
NAME=""

while [ $# -gt 0 ]; do
  case "$1" in
    --hw-config)  HW_CONFIG="$2"; shift 2;;
    --workload)   WORKLOAD="${2%.json}"; shift 2;;
    --bootbinary) BOOTBINARY="$2"; shift 2;;
    --outputs)    OUTPUTS="$2"; shift 2;;
    --run-host)   RUN_HOST="$2"; shift 2;;
    --sim-dir)    SIM_DIR="$2"; shift 2;;
    --fpga-db)    FPGA_DB="$2"; shift 2;;
    --name)       NAME="$2"; shift 2;;
    -h|--help)    sed -n '2,40p' "${BASH_SOURCE[0]}"; exit 0;;
    *) echo "unknown option: $1" >&2; exit 1;;
  esac
done

# default config name: "local" for localhost, else the host label before the dot
if [ -z "$NAME" ]; then
  if [ "$RUN_HOST" = "localhost" ]; then NAME="local"; else NAME="${RUN_HOST#*@}"; NAME="${NAME%%.*}"; fi
fi

CFG="$DEPLOY/config_runtime_${NAME}.yaml"
WJSON="$DEPLOY/workloads/${WORKLOAD}.json"
mkdir -p "$DEPLOY/workloads"

# ---- run-farm host block: localhost vs remote SSH (+ optional fpga_db) ----
FPGA_DB_LINE=""
[ -n "$FPGA_DB" ] && FPGA_DB_LINE="    default_fpga_db: ${FPGA_DB}"
if [ "$RUN_HOST" = "localhost" ]; then
  HOSTS_LINE="      - localhost: one_fpga_spec"
else
  HOSTS_LINE="      - \"${RUN_HOST}\": one_fpga_spec"
fi

# ---- common_simulation_outputs JSON array from the space-separated list ----
OUT_JSON=$(printf '"%s", ' $OUTPUTS); OUT_JSON="[ ${OUT_JSON%, } ]"

cat > "$WJSON" <<EOF
{
  "benchmark_name": "${WORKLOAD}",
  "common_simulation_outputs": ${OUT_JSON},
  "common_bootbinary": "${BOOTBINARY}",
  "common_rootfs": "dummy.rootfs"
}
EOF

cat > "$CFG" <<EOF
# RUNTIME configuration for the FireSim Simulation Manager — GENERATED by
# soc/scripts/gen_firesim_run_config.sh (do not commit; paths are environment-specific).
run_farm:
  base_recipe: run-farm-recipes/externally_provisioned.yaml
  recipe_arg_overrides:
    default_platform: XilinxAlveoU250InstanceDeployManager
    default_simulation_dir: ${SIM_DIR}
${FPGA_DB_LINE}
    run_farm_host_specs:
      - one_fpga_spec:
          num_fpgas: 1
          num_metasims: 1
          use_for_switch_only: 0
      - one_metasims_spec:
          num_fpgas: 0
          num_metasims: 1
          use_for_switch_only: 0
      - two_metasims_spec:
          num_fpgas: 0
          num_metasims: 2
          use_for_switch_only: 0
    run_farm_hosts_to_use:
${HOSTS_LINE}
metasimulation:
  metasimulation_enabled: false
  metasimulation_host_simulator: vcs-debug
  metasimulation_only_plusargs: "+fesvr-step-size=128 +max-cycles=100000000"
  metasimulation_only_vcs_plusargs: "+vcs+initreg+0 +vcs+initmem+0"
target_config:
  topology: no_net_config
  no_net_num_nodes: 1
  link_latency: 6405
  switching_latency: 10
  net_bandwidth: 200
  profile_interval: -1
  default_hw_config: ${HW_CONFIG}
  plusarg_passthrough: "+partitioned=1"
tracing:
  enable: no
  output_format: 0
  selector: 1
  start: 0
  end: -1
autocounter:
  read_rate: 0
workload:
  workload_name: ${WORKLOAD}.json
  terminate_on_completion: no
  suffix_tag: null
host_debug:
  zero_out_dram: no
  disable_synth_asserts: no
synth_print:
  start: 0
  end: -1
  cycle_prefix: yes
EOF

# strip a possible blank fpga_db line so the yaml stays clean
sed -i '/^$/N;/^\n$/D' "$CFG" 2>/dev/null || true

echo "generated:"
echo "  $CFG"
echo "  $WJSON"
echo
echo "next: cd $ROSE_ROOT/soc/sim/chipyard/sims/firesim"
echo "      source env.sh && source sourceme-manager.sh --skip-ssh-setup"
echo "      firesim infrasetup  -c $(basename "$CFG")"
echo "      firesim runworkload -c $(basename "$CFG")"
